/* TYPES FOR PRODUCTREDUCER*/
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const PRODUCTS_SORTED_HIGHEST = 'PRODUCTS_SORTED_HIGHEST';
export const PRODUCTS_SORTED_LOWEST = 'PRODUCTS_SORTED_LOWEST';
export const PRODUCTS_SORTED_PREDEFINED = 'PRODUCTS_SORTED_PREDEFINED';
export const AFFORDABLE_ARRAY = 'AFFORDABLE_ARRAY ';
export const UNAFFORDABLE_ARRAY = 'UNAFFORDABLE_ARRAY ';

/*TYPER FOR USERREDUCER*/
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';